### ISSUE TITLE
What is this for?

### ISSUE THREAD

**Issue by p0nce** [avaneev/gammaenv#1]
It looks like a kind of smoothing that would be better than a simple exponential attack-release decay?

**Comment by avaneev** [comment]
Re: [avaneev/gammaenv] What is this for? (#1)

Greetings,

Yes, it is.

Best regards,
Aleksey Vaneev
http://www.voxengo.com/

---

Thursday, August 11, 2016, 4:08:12 PM, you wrote:

It looks like a kind of smoothing that would be better than a simple exponential attack-release decay?

**Comment by p0nce** [comment]
Thanks.
